version: "3.8"
services: 
  mongodb: 
    image: mongo:latest
    ports:
      - 27018:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: pass 
      
    volumes:
      - ./mongo_data:/var/lib/mongodb/data
    restart: always 
