services: 
  mongodb: 
    image: mongo:latest
    ports:
      - 27018:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: pass 
      
    volumes:
      - ./mongo_data:/var/lib/mongodb/data
    restart: always 
    
  api:
    build: .
    environment:
      - PYTHONUNBUFFERED=1
      - MONGODB_URI=mongodb://root:pass@mongodb
    ports:
      - 8080:8080
    depends_on:
      - mongodb

